global-settings
{
	watch-config-file = false;
}

bar
{
	output            = eDP-1;
	position          = bottom;
	background-colour = "#202020";
	border-colour     = "#CBB68C";
	border      = 2;

	# Condition for the default configuration set.
	condition-resolution = wider-than-high;
	size = 60;
	layer = overlay;
	exclusive-zone = off;
	hidden-mode = always;
	radius = 5;

	config
	{
		# Condition for this configuration set.
		condition-resolution = higher-than-wide;

		# Additional configuration sets copy the default configuration set,
		# but settings can be overwritten.
		position = left;
	}

	button
	{
		image-path = ~/crystal-dots/.config/lavalauncher/icon/discord.png;
		command    = discord;
	}
	button
	{
		image-path = ~/crystal-dots/.config/lavalauncher/icon/firefox.png;
		command    = firefox;
	}
	button
	{
		image-path = ~/crystal-dots/.config/lavalauncher/icon/github.png;
		command    = firefox "https://github.com/";
	}
	button
	{
		image-path = ~/crystal-dots/.config/lavalauncher/icon/terminal.png;
		command    = foot;
	}
	button
	{
		image-path = ~/crystal-dots/.config/lavalauncher/icon/youtube.png;
		command    = firefox "https://www.youtube.com/";
	}
	}
